/* eslint-disable sonarjs/no-duplicate-string */
export class Attributes {
  static traits() {
    return Object.keys(this.toObject());
  }

  static toObject() {
    return {
      Avatar: [...this.Avatar],
      Background: [...this.Background],
      MaxisRing: [...this.MaxisRing],
      Body: [...this.Body],
      Head: [...this.Head],
      Eyes: [...this.Eyes],
      Mouth: [...this.Mouth],
      Hair: [...this.Hair],
      Clothing: [...this.Clothing],
      Nose: [...this.Nose],
      Eyewear: [...this.Eyewear],
      Accessory: [...this.Accessory],
      Headwear: [...this.Headwear],
    };
  }

  static Avatar = [
    'Zombie',
    'Male',
    'Female',
    'AliENS',
    'Panda',
    'Ape',
    'Numbers Guy',
    'Ethmoji',
    'Cheetah',
    'Kangaroo',
  ] as const;

  static Background = [
    'Bubbles',
    'Purple',
    'Dark Grey',
    'Magenta',
    'Wallpaper',
    'Pink',
    'Orange',
    'Passionfruit',
    'Dark Web',
    'Yellow',
    'Blue',
    'Red',
    'Textured Green',
    'Picasso',
    'Matrix (Gold)',
    'Matrix (Green)',
    'Stars',
    'Space Travel',
  ] as const;

  static MaxisRing = [
    'Golden',
    'Metal',
    'Green',
    'Galaxy',
    'Orange',
    'Trippy',
    'Sky Blue',
    'Charcoal',
    'Crocodile Skin',
    'Aquamarine',
    'Purple',
    'Yellow',
    'Robot',
    'Grey',
    'Pink',
    'Jungle',
    'Electric',
    '420',
    'Magenta',
    'Diamond',
    'Zombie Slayer',
    'Worldwide',
    'Flames',
  ] as const;

  static Body = [
    'Zombie',
    'Dark',
    'Medium',
    'Light',
    'Blue Martian',
    'Panda',
    'Ape',
    'Tatted Ape',
    'Numbers Guy (Medium)',
    'Ethmoji',
    'Cheetah',
    'Kangaroo',
    'Numbers Guy (Light)',
    'Numbers Guy (Dark)',
  ] as const;

  static Head = [
    'Zombie',
    'Dark',
    'Medium',
    'Ear Bitten Off',
    'Light',
    'Blue Martian',
    'Panda',
    'Ape',
    'Beats by Martian',
    'Numbers Guy (Medium)',
    'Ethmoji',
    'Cheetah',
    'You Should See The Other Guy',
    'Numbers Guy (Light)',
    'Kangaroo',
    'Numbers Guy (Dark)',
  ] as const;

  static Eyes = [
    'Hanging Eye',
    'Determined',
    'Dafuq',
    'Serious Wink',
    'Stern',
    'Crazed',
    'Stare',
    'Mutation',
    'Furious',
    'Lava',
    'Purple Haze',
    'Angry',
    'Wink',
    'Panda',
    'Rage',
    'White',
    'Lantern',
    'Scar',
    'War',
    'Numbers Guy',
    'Ethmoji',
    'Cheetah',
    'Kangaroo',
    'Kangaroo (Punched)',
  ] as const;

  static Mouth = [
    'Cuban',
    'Bubblegum',
    'Smile',
    'Kiss',
    'Bearded Carnivore',
    'Gold Tooth',
    'Pissed',
    'Juicy Lips',
    'Happy',
    'Mutant Drool',
    'Carnivore',
    'Beep-Bop',
    'Cheese',
    'Seductive',
    'Panda',
    'Moustache',
    'Oooo-oo-ahh-ah',
    'Scream',
    'Flesh Eater',
    'Pearly Whites',
    'Laughing',
    'Numbers Guy',
    'Ethmoji',
    'Cheetah',
    'Kangaroo',
    'Kangaroo (Punched)',
  ] as const;

  static Hair = [
    'Hazard',
    'Lucky Charms',
    'Afro Puff',
    'Fade',
    'Braids',
    'Fuqboi',
    'Electric Blue',
    'Highlights',
    'Wavy',
    'Octopus',
    'Blue',
    'High Top',
    'Pixie Cut',
    'Chun Li Buns',
    'Bald',
    'Redhead',
    'Fro',
    'Sh-Ape',
    'Pink Hair',
    'Dreads',
    'Great Ape Ponytail',
    'Open Brain',
    'The Dino',
    'Slicked Back',
    'Ponytail',
  ] as const;

  static Clothing = [
    'Walking Dead Sheriff',
    'Beach Tank Top',
    'Tube Top',
    'Black Hoodie',
    'Hoodie',
    'Leather Jacket',
    'Kung Fu Suit',
    'ENS Blouse',
    'Punks Jacket',
    'ENS Tank Top',
    'ENS Tactical',
    'ENS Army Tee',
    'Cheongsam',
    'Letterman Jacket',
    'Miami Vibes',
    'Blue Kimono',
    'ENS Tee',
    'Summer Graphic Tee',
    'Orange T-Shirt',
    'Tie-Dye Top',
    'Reptile T-Shirt',
    'Saturn Tank Top',
    'White Tank Top (Ripped)',
    'Ripped',
    'Black T-Shirt',
    'DBZ',
    'Tux',
    'Kandura',
  ] as const;

  static Nose = [
    'Zombie Nose',
    'Default',
    'Runny Nose',
    'No Nose Ring',
  ] as const;

  static Eyewear = [
    'Punk Glasses',
    'Green Shades',
    'Blue Shades',
    'Futuristic Glasses',
    'Shades',
    'Third Eye',
    'Laugh Tears',
    'Golden Glasses',
    'Steampunk Shades',
  ] as const;

  static Accessory = [
    'Silver Earring',
    'Piercing',
    'Skull Piercing',
    'Hoops',
    'Nose Ring',
    'Gold Nose Ring',
    'FUD U Tattoo',
    'Gold Chain',
    'Gold Earring',
    'Septum Nose Ring',
    'Ginger Goatee',
    'DBZ',
    'Mutant Earwax',
    'Dog Tag',
    'Bamboo',
    'Bitten Coin',
    '10k Earring',
    'Boxing Gloves',
    '999 Set',
  ] as const;

  static Headwear = [
    'Red Cap',
    'Astro Helmet',
    'Bandana',
    'Ethmoji Hat',
    'Army Helmet',
    'Headphones',
    'Beanie',
    'Cat Ears',
    'Crown',
    'Digital Headwear',
    'QueENS Crown',
    'Heisenberg',
    'Barbed Wire',
    'Banana Sweat Band',
    'Australian Hat',
    'Keffiyeh',
    'Sedge Hat',
    'Poker Hat',
  ] as const;
}
